apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "simple-kubernetes-webhook.acme.com"
webhooks:
  - name: "simple-kubernetes-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: simple-kubernetes-webhook
        path: /validate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRekNDQWl1Z0F3SUJBZ0lVWEdya3RqbmpO
        WU1heDU0TGlrQjNIL3NCeHlzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URUxNQWtHQTFVRUJoTUNR
        VlV4SWpBZ0JnTlZCQU1NR1hOcGJYQnNaUzFyZFdKbGNtNWxkR1Z6TFhkbApZbWh2YjJzd0hoY05N
        akl4TVRBM01EZ3lNVFU1V2hjTk1qTXhNVEEzTURneU1UVTVXakF4TVFzd0NRWURWUVFHCkV3SkJW
        VEVpTUNBR0ExVUVBd3daYzJsdGNHeGxMV3QxWW1WeWJtVjBaWE10ZDJWaWFHOXZhekNDQVNJd0RR
        WUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1VSWldOUkdzYkd6QytmSlRrSlBa
        U21jWE5pRWpqaApNenlMVTRrdEdodUxKbWEwRS9DZ3Nvb0ZDWnFiQ25kdUp0ZFVmcXdISXJYYko2
        aGh5ZFpGeWFkd2dIbzF2UG40CllhRW9YN0pwSDZOQm9jMERweS90M1c2UzBEM2VGbEQ5MGRLN1pX
        U1VlVWNWemcyaFVGVE11QVlQaXZRQ2V1YzYKZ3I5MVQweUdnZElmL0I3MzkxMDdISlZQY09YTEx5
        aHdBbERlWDVXU0xKbHFVcE82WVlSci9xcjNlOXptclp1NwprMklaQlJEa0JTaGNUUTQwM2Y5dGZU
        OEV4ZHlJZElaUG5LN3pjclpCRExmWkhFWWRQQXVwNUhKanFYNlgwWWJRClZ4QUZmMSsvL24vVVdP
        TTVYL3BIUkhLdlB6ZXdiNWJ2TFpwTmlLTzNnV2JJeThyNnpXRyswOWtDQXdFQUFhTlQKTUZFd0hR
        WURWUjBPQkJZRUZKdGpDSmEvNW81SHVZclhVYklOT2F6Q3RwV0pNQjhHQTFVZEl3UVlNQmFBRkp0
        agpDSmEvNW81SHVZclhVYklOT2F6Q3RwV0pNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29a
        SWh2Y05BUUVMCkJRQURnZ0VCQU5nTnhKbnBUWVVXS05qWml0Mm45alF5ZWpRWjVrcnBnYWNiZ0dW
        NUxzbmE2NGVjbVo5OXRWQWQKNFNTWW95ZGNOdnRzMStwVGlVaCtvR3hPd2pZamxDcHEwaVZiZU4v
        M0NSaTdwa1k0OFh3RFBlTURmYzArZ1czLwpPdUdScDhqNWNFc3R1Q1VLaXJlVTJlbGFtTlNjc1dm
        ekdrditPbVcwWEVpcEFJWE4yTTlhaXZXT1F1MlhNcFc0CnMzNFFwYkhoMktiemVmcnU4b2RmOFFk
        dG52NVVVcjBqWkphVllZQW00Y2VzUGtCOW5yTmNTSnhwL0diVWN3S2EKU1Jac1RQTFJBalF5Q1Mx
        Z0hqMlQyb3ZtRXNYL3R3V0lOYjlhQUFQdGc1bXB1a2ZTdEFlMm1ydktwS3pJRzJOMwpmK2lpUGR3
        dFM4SXhWc25vaXJQaVE5SFczd3phRE13PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 30
